"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
"""

from .lcmt_robotiq_input import lcmt_robotiq_input
from .lcmt_robotiq_output import lcmt_robotiq_output
